### ISSUE TITLE
Unable to  save data received from Azure IoT hub to a variable

### ISSUE THREAD

**Issue by aravindhswaminathan** [br-automation-com/AzureSDK_Library#1]
I am trying to save the data received by B&R plc from Azure IoT hub to a variable. Every time the data is received from IoT hub, I want to check the string received and update a particular variable based on the string received.  

I believe  the below section is where I need to work on. 

 // AMQP message content.
    IOTHUBMESSAGE_CONTENT_TYPE contentType = IoTHubMessage_GetContentType(message);

    if (contentType == IOTHUBMESSAGE_BYTEARRAY)
    {
        if (IoTHubMessage_GetByteArray(message, &buffer, &size) == IOTHUB_MESSAGE_OK)
        {
            ArLogInfo("Received Message [%d] (message-id: %s, correlation-id: %s) with BINARY Data: <<<%.*s>>> & Size=%d\r\n", *counter, messageId, correlationId,(int)size, buffer, (int)size);
			//temp = &buffer;
			//ArLogInfo("temp variable value: [%s] \r\n", temp);
        }
        else
        {
            ArLogError("Failed getting the BINARY body of the message received.\r\n");
        }
    }
    else if (contentType == IOTHUBMESSAGE_STRING)
    {
        if ((buffer = (const unsigned char*)IoTHubMessage_GetString(message)) != NULL && (size = strlen((const char*)buffer)) > 0)
        {
            ArLogInfo("Received Message [%d] (message-id: %s, correlation-id: %s) with STRING Data: <<<%.*s>>> & Size=%d\r\n", *counter, messageId, correlationId, (int)size, buffer, (int)size);
			//temp = &buffer;
            // If we receive the work 'quit' then we stop running
        }
        else
        {
            ArLogError("Failed getting the STRING body of the message received.\r\n");
        }
    }

Kindly help to check. 

Thanks.

**Comment by patricthysell** [comment]
Sorry for the extremely late answer.. In most cases you receive JSON data from the IotHub, meaning you need to parse that, then put it into a variable.. 

Try and see if
**[https://github.com/br-automation-com/PvJson](https://github.com/br-automation-com/PvJson)

can help with that
